# Generated by Django 3.1.5 on 2021-01-21 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppinglouis', '0003_productshoppinglist_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productshoppinglist',
            name='quantity',
        ),
    ]
